### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Floodo** [InstantlyMoist/Gameboy#3]
Hi, i just put plugin in plugin folder, and start server. And while server was loading the plugin, this error message pops up.
Server 1.19 (Paper, Waterfall + Geyser)

[23:01:56 INFO]: [Gameboy] Enabling Gameboy v1.17
[23:01:56 ERROR]: Error occurred while enabling Gameboy v1.17 (Is it up to date?)
java.lang.NumberFormatException: For input string: "19)"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at me.kyllian.gameboy.handlers.map.MapHandlerFactory.getMapHandler(MapHandlerFactory.java:16) ~[Gameboy.jar:?]
        at me.kyllian.gameboy.GameboyPlugin.onEnable(GameboyPlugin.java:41) ~[Gameboy.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-81]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:01:56 INFO]: [Gameboy] Disabling Gameboy v1.17

What should I do? :( 

Thank you :)

**Comment by InstantlyMoist** [comment]
Hi, 

Can you join my discord please so I can help you easier?

https://kyllian.nl/discord
